# Generated by Django 3.0.7 on 2021-05-08 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('queue_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('store_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.TextField(max_length=200)),
                ('store_phone', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store_q',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('capacity', models.IntegerField(default=100)),
                ('url', models.URLField()),
                ('average_waiting_time_for_person', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'stores',
            },
        ),
        migrations.CreateModel(
            name='Queue_q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queuedate', models.DateField()),
                ('current_customer_in_store', models.IntegerField(default=0)),
                ('current_waiting_time', models.IntegerField(default=0)),
                ('number_people_waiting', models.IntegerField(default=0)),
                ('first_customer_queue_id', models.IntegerField(default=0)),
                ('last_customer_queue_id', models.IntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidatabase.Store_q')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_queue_id', models.IntegerField(default=0)),
                ('first_name', models.CharField(default='XXX', max_length=50)),
                ('last_name', models.CharField(default='YYY', max_length=50)),
                ('phone', models.CharField(default='XXX-XXX-XXXX', max_length=50)),
                ('number_of_people', models.IntegerField(default=-1)),
                ('join_time', models.TimeField(auto_now_add=True)),
                ('potential_wait_time', models.IntegerField(default=-1)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidatabase.Queue_q')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidatabase.Store_q')),
            ],
        ),
    ]
