# Generated by Django 3.0.7 on 2021-05-09 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=128, unique=True)),
                ('store_capacity', models.IntegerField(default=100)),
                ('store_url', models.URLField()),
                ('store_average_waiting_time_for_person', models.IntegerField(default=0)),
                ('store_current_count', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'stores',
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queuedate', models.DateField()),
                ('current_waiting_time', models.IntegerField(default=0)),
                ('number_people_waiting', models.IntegerField(default=0)),
                ('first_Customerueue_id', models.IntegerField(default=0)),
                ('last_Customerueue_id', models.IntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidatabase.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customerueue_id', models.IntegerField(default=0)),
                ('first_name', models.CharField(default='XXX', max_length=50)),
                ('last_name', models.CharField(default='YYY', max_length=50)),
                ('phone', models.CharField(default='XXX-XXX-XXXX', max_length=50)),
                ('number_of_people', models.IntegerField(default=-1)),
                ('join_time', models.TimeField(auto_now_add=True)),
                ('potential_wait_time', models.IntegerField(default=-1)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidatabase.Queue')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidatabase.Store')),
            ],
        ),
    ]
