# Generated by Django 3.2 on 2021-05-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store_q',
            old_name='average_waiting_time_for_person',
            new_name='store_average_waiting_time_for_person',
        ),
        migrations.RenameField(
            model_name='store_q',
            old_name='capacity',
            new_name='store_capacity',
        ),
        migrations.RenameField(
            model_name='store_q',
            old_name='name',
            new_name='store_name',
        ),
        migrations.RenameField(
            model_name='store_q',
            old_name='url',
            new_name='store_url',
        ),
        migrations.RemoveField(
            model_name='queue_q',
            name='current_customer_in_store',
        ),
        migrations.AddField(
            model_name='store',
            name='password',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='store',
            name='store_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='store_current_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store_q',
            name='store_current_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_phone',
            field=models.TextField(default=0, max_length=20),
        ),
    ]
