# Generated by Django 3.0.7 on 2021-05-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store_q',
            old_name='url',
            new_name='store_url',
        ),
    ]
