# Generated by Django 3.2.7 on 2021-09-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_code', models.CharField(max_length=20)),
                ('ad_image', models.ImageField(upload_to='queueweb/static/')),
                ('ad_description', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
