# Generated by Django 3.2 on 2021-05-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='password',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='store',
            name='store_phone',
            field=models.TextField(default='0', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.TextField(max_length=200),
        ),
    ]
