# Generated by Django 3.2.7 on 2021-09-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='thermal_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='thermal_task_queue',
            field=models.IntegerField(default=0),
        ),
    ]
