# Generated by Django 2.2.12 on 2021-04-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='id',
        ),
        migrations.AddField(
            model_name='queue',
            name='queue_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='store',
            name='store_phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='store_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
