# Generated by Django 3.0.7 on 2021-05-04 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0002_auto_20210423_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('capacity', models.IntegerField(default=100)),
                ('url', models.URLField()),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'stores',
            },
        ),
        migrations.CreateModel(
            name='Queue_q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queuedate', models.DateField()),
                ('current_waiting_time', models.IntegerField(default=0)),
                ('number_people_waiting', models.IntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidatabase.Store_q')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='XXX', max_length=50)),
                ('last_name', models.CharField(default='YYY', max_length=50)),
                ('phone', models.CharField(default='XXX-XXX-XXXX', max_length=50)),
                ('number_of_people', models.IntegerField(default=-1)),
                ('join_time', models.IntegerField(default=-1)),
                ('current_waiting_time_individual', models.IntegerField(default=-1)),
                ('potential_wait_time', models.IntegerField(default=-1)),
                ('real_wait_time', models.IntegerField(default=-1)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidatabase.Queue_q')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidatabase.Store_q')),
            ],
        ),
    ]
