# Generated by Django 3.2.7 on 2021-09-13 03:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0002_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='store_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apidatabase.store'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='ad_image',
            field=models.ImageField(upload_to='queueweb/media/'),
        ),
    ]
