# Generated by Django 3.2 on 2021-10-16 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0002_auto_20210914_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='vaccination_card',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
