# Generated by Django 3.2 on 2021-05-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0002_auto_20210423_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='password',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='store',
            name='store_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='store_current_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_phone',
            field=models.TextField(max_length=20),
        ),
    ]
