# Generated by Django 3.0.7 on 2021-05-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0002_auto_20210508_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store_q',
            old_name='average_waiting_time_for_person',
            new_name='store_average_waiting_time_for_person',
        ),
    ]
