# Generated by Django 3.0.7 on 2021-05-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0003_customer_q_queue_q_store_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue_q',
            name='queuedate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
