# Generated by Django 3.0.7 on 2021-05-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0003_auto_20210508_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store_q',
            old_name='name',
            new_name='store_name',
        ),
    ]
