# Generated by Django 3.0.7 on 2021-09-14 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0003_auto_20210912_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('promo_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.IntegerField(default=0)),
                ('promo_code', models.CharField(max_length=20)),
                ('wait_time', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=False)),
                ('promo_description', models.CharField(default='', max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidatabase.Store')),
            ],
        ),
    ]
