# Generated by Django 3.0.7 on 2021-09-21 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0004_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='time_get_access',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
