# Generated by Django 3.0.7 on 2021-05-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0004_auto_20210505_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue_q',
            name='queuedate',
            field=models.DateField(),
        ),
    ]
