# Generated by Django 3.0.7 on 2021-05-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0004_auto_20210508_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store_q',
            old_name='capacity',
            new_name='store_capacity',
        ),
    ]
