# Generated by Django 3.0.7 on 2021-09-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0005_customer_time_get_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='time_get_access',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
