# Generated by Django 3.0.7 on 2021-05-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0005_auto_20210505_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_q',
            name='join_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
