# Generated by Django 3.0.7 on 2021-05-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0005_auto_20210508_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_q',
            name='store_current_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
