# Generated by Django 3.0.7 on 2021-05-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0006_auto_20210505_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_q',
            name='customer_queue_id',
            field=models.IntegerField(default=0),
        ),
    ]
