# Generated by Django 3.0.7 on 2021-05-09 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0006_store_q_store_current_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue_q',
            name='current_customer_in_store',
        ),
    ]
