# Generated by Django 3.0.7 on 2021-09-21 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0007_auto_20210921_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='join_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
