# Generated by Django 3.0.7 on 2021-05-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0008_auto_20210505_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_q',
            name='current_waiting_time_individual',
        ),
        migrations.RemoveField(
            model_name='customer_q',
            name='real_wait_time',
        ),
        migrations.AddField(
            model_name='store_q',
            name='average_waiting_time_for_person',
            field=models.IntegerField(default=0),
        ),
    ]
