# Generated by Django 3.2 on 2021-10-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0003_store_vaccination_card'),
        ('apidatabase', '0008_auto_20210921_0719'),
    ]

    operations = [
    ]
