# Generated by Django 3.0.7 on 2021-05-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0009_auto_20210505_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue_q',
            name='current_customer_in_store',
            field=models.IntegerField(default=0),
        ),
    ]
