# Generated by Django 3.2 on 2021-10-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0010_auto_20211027_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_current_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
