# Generated by Django 3.2 on 2021-10-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0011_store_store_current_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_average_waiting_time_for_person',
            field=models.IntegerField(default=0),
        ),
    ]
