# Generated by Django 3.2 on 2021-12-02 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apidatabase', '0012_store_store_average_waiting_time_for_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='vaccination_card',
        ),
        migrations.CreateModel(
            name='VaccinationCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_card', models.TextField()),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidatabase.store')),
            ],
        ),
    ]
